% -------------------------------------------------------------------
%  Generated by MATLAB on 15-Sep-2023 16:31:36
%  MATLAB version: 23.2.0.2365128 (R2023b)
% -------------------------------------------------------------------
saveVarsMat = load('MonteCarlos_European.mat');

S0 = 100;

Sb = 48;

Sf = saveVarsMat.Sf; % <1x1000000 double> too many elements

T = 1;

X = 100;

ans = 1.7150388932515515;

blsCall = 10.450583572185565;

blsPut = 5.5735260222569707;

dt = 0.0027397260273972603;

elapsedTime = 0.016849049;

etime = 365;

idx = 1.0E+6;

nruns = [1000 10000 100000 1.0E+6];

nu = 0.03;

payoffT = saveVarsMat.payoffT; % <1x10000 double> too many elements

r = 0.05;

sig = 0.2;

str = ['For 1000000 simulations: Price = 10.4408.  Execution time = 0.0' ...
       '16849.'];

value = 10.440824421404045;

clear saveVarsMat;
